target_repo: quay.io/bradfordwagner/template-mirror
mirrors:
  - repo: alpine
    platforms:
      - linux/amd64
      - linux/arm64
    tag: latest
  - repo: alpine
    platforms:
      - linux/amd64
      - linux/arm64
    tag: '3.19'
  - repo: debian
    platforms:
      - linux/amd64
      - linux/arm64
    tag: bookworm
  - repo: debian
    platforms:
      - linux/amd64
      - linux/arm64
    tag: bullseye
  - repo: ubuntu
    platforms:
      - linux/amd64
      - linux/arm64
    tag: noble
  - repo: ubuntu
    platforms:
      - linux/amd64
      - linux/arm64
    tag: mantic
  - repo: ubuntu
    platforms:
      - linux/amd64
      - linux/arm64
    tag: jammy
