target_repo: quay.io/bradfordwagner/template-mirror
mirrors:
  - repo: alpine
    platforms:
      - linux/amd64
      - linux/arm64
    tag: latest
  - repo: alpine
    platforms:
      - linux/amd64
      - linux/arm64
    tag: '3.19'
