name: container-tags
on:
  push:
    tags:
      - '*'
env:
  version: ${{ github.ref_name }}
jobs:
  product:
    name: product
    runs-on: ubuntu-latest
    outputs:
      product: ${{ steps.config.outputs.product }}
    steps:
      - uses: actions/checkout@v4
      - name: dagger=0.15.2
        run: |
          curl -L https://dl.dagger.io/dagger/install.sh | DAGGER_VERSION=0.15.2 sh
      - name: dagger=product
        id: config
        run: |
          # write your own scoped version of the following since https://github.com/bradfordwagner/dagger-container-builds@0.1.1 is not available at this base level
          set -x
          echo product=$(./bin/dagger -m https://github.com/bradfordwagner/dagger-container-builds@0.1.1 call product-json --src=. --version=${{ env.version }}) >> $GITHUB_OUTPUT
  builds:
    runs-on: ${{ matrix.product.runner }}
    permissions: write-all
    needs: product
    name: ${{ matrix.product.display }}
    strategy:
      fail-fast: false
      matrix:
        product: ${{ fromJSON(needs.product.outputs.product) }}
    steps:
      - uses: actions/checkout@v4
      - name: dagger=0.15.2
        run: |
          curl -L https://dl.dagger.io/dagger/install.sh | DAGGER_VERSION=0.15.2 sh
      
      # work around other runner's logging out removing credentials
      # https://github.com/docker/login-action/issues/173#issuecomment-1079688020
      - name: Set DOCKER_CONFIG
        run: |
          id=docker_configs/${RANDOM}
          mkdir -p $HOME/${id}/.docker
          echo "DOCKER_CONFIG=$HOME/${id}/.docker" >> $GITHUB_ENV
      - uses: docker/login-action@v3
        name: login=ghcr.io
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: false
      - name: dagger=build
        id: config
        run: |
          ./bin/dagger -m https://github.com/bradfordwagner/dagger-container-builds@0.1.1 call build \
            --progress=plain \
            --src=. \
            --index=${{ matrix.product.index }} \
            --version=${version}
  manifest:
    runs-on: ubuntu-latest
    permissions: write-all
    needs: builds
    name: manifest-tool
    env:
      actor: ${{ github.actor }}
      token: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
      - name: dagger=0.15.2
        run: |
          curl -L https://dl.dagger.io/dagger/install.sh | DAGGER_VERSION=0.15.2 sh
      # work around other runner's logging out removing credentials
      # https://github.com/docker/login-action/issues/173#issuecomment-1079688020
      - name: Set DOCKER_CONFIG
        run: |
          id=docker_configs/${RANDOM}
          mkdir -p $HOME/${id}/.docker
          echo "DOCKER_CONFIG=$HOME/${id}/.docker" >> $GITHUB_ENV
      - uses: docker/login-action@v3
        name: login=ghcr.io
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: false
      - name: dagger=manifest
        id: config
        run: |
          set -x
          ./bin/dagger -m https://github.com/bradfordwagner/dagger-container-builds@0.1.1 call manifest \
            --src=. \
            --version=${version} \
            --actor=env:actor \
            --token=env:token
