name: docker-mirror-tags
on:
  push:
    tags:
      - '*'
jobs:
  alpine_latest_tags:
    name: alpine:latest
    runs-on: ubuntu-latest
    steps:
      - name: checkout=self
        uses: actions/checkout@v4
      - name: task=3.35.1
        uses: pnorton5432/setup-task@v1
        with:
          task-version: 3.35.1
      - name: checkout=taskfiles
        uses: actions/checkout@v4
        with:
          path: taskfiles
          repository: bradfordwagner/taskfiles
      - name: qemu
        uses: docker/setup-qemu-action@v3
      - name: docker_buildx=v0.13.1
        uses: docker/setup-buildx-action@v3
        with:
          version: v0.13.1
      - name: login=quay.io
        run: docker login -u="${{ secrets.QUAY_USER }}" -p="${{ secrets.QUAY_PASSWORD }}" quay.io
      - name: task=tags
        run: |
          
          task -t ./taskfiles/tasks/containers/mirror.yml             build             repo=alpine             repo_tag=latest             platforms=linux/amd64,linux/arm64             target_repo=quay.io/bradfordwagner/template-mirror             target_tag=${{ github.ref }}             is_tag=true

  alpine_3-19_tags:
    name: alpine:3.19
    runs-on: ubuntu-latest
    steps:
      - name: checkout=self
        uses: actions/checkout@v4
      - name: task=3.35.1
        uses: pnorton5432/setup-task@v1
        with:
          task-version: 3.35.1
      - name: checkout=taskfiles
        uses: actions/checkout@v4
        with:
          path: taskfiles
          repository: bradfordwagner/taskfiles
      - name: qemu
        uses: docker/setup-qemu-action@v3
      - name: docker_buildx=v0.13.1
        uses: docker/setup-buildx-action@v3
        with:
          version: v0.13.1
      - name: login=quay.io
        run: docker login -u="${{ secrets.QUAY_USER }}" -p="${{ secrets.QUAY_PASSWORD }}" quay.io
      - name: task=tags
        run: |
          
          task -t ./taskfiles/tasks/containers/mirror.yml             build             repo=alpine             repo_tag=3.19             platforms=linux/amd64,linux/arm64             target_repo=quay.io/bradfordwagner/template-mirror             target_tag=${{ github.ref }}             is_tag=true

