name: docker-mirror-tags
on:
  push:
    tags:
      - '*'
env:
  version: ${{ github.ref_name }}
jobs:
  config-yaml:
    name: config.yaml
    runs-on: arm64
    outputs:
      product: ${{ steps.config.outputs.product }}
    steps:
      - uses: actions/checkout@v4
      - name: dagger=install
        run: |
          curl -L https://dl.dagger.io/dagger/install.sh | DAGGER_VERSION=0.11.8 sh
      
      - name: dagger=product
        id: config
        run: |
          echo product=$(./bin/dagger -m github.com/bradfordwagner/dagger-modules/container_mirror@feature/init call product-json --src=.) >> $GITHUB_OUTPUT
  builds:
    runs-on: ${{ matrix.product.runner }}
    permissions: write-all
    needs: config-yaml
    name: ${{ matrix.product.index }}:${{ matrix.product.repo }}-${{ matrix.product.tag }} (${{ matrix.product.arch }})
    strategy:
      fail-fast: false
      matrix:
        product: ${{ fromJSON(needs.config-yaml.outputs.product) }}
    steps:
      - uses: actions/checkout@v4
      - name: dagger=install
        run: |
          curl -L https://dl.dagger.io/dagger/install.sh | DAGGER_VERSION=0.11.8 sh
      
      - uses: docker/login-action@v3
        name: login=ghcr.io
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: dagger=build
        id: config
        run: |
          ./bin/dagger -m github.com/bradfordwagner/dagger-modules/container_mirror@feature/init call build \
            --src=. \
            --index=${{ matrix.product.index }} \
            --version=${version} \
            --isDev=false
  manifest:
    runs-on: arm64
    permissions: write-all
    needs: builds
    name: manifest
    steps:
      - uses: actions/checkout@v4
      - name: dagger=install
        run: |
          curl -L https://dl.dagger.io/dagger/install.sh | DAGGER_VERSION=0.11.8 sh
      - name: dagger=manifest
        id: config
        run: |
          ./bin/dagger -m github.com/bradfordwagner/dagger-modules/container_mirror@feature/init call manifest \
            --src=. \
            --version=${version} \
            --actor=${{ github.actor }} \
            --token=${{ github.token }}
