name: docker-mirror-tags
on:
  push:
    tags:
      - '*'
jobs:
  config-yaml:
    name: config.yaml
    runs-on: arm64
    outputs:
      products: ${{ steps.config.outputs.products }}
    steps:
      - uses: actions/checkout@v4
      # - name: export=config
      #   id: config
      #   run: echo "config=$(yq -oj '.' config.yaml | jq -cr)" >> $GITHUB_OUTPUT
      - name: dagger=install
        run: |
          curl -L https://dl.dagger.io/dagger/install.sh | DAGGER_VERSION=0.11.8 sh
      - name: dagger=product
        id: config
        run: |
          echo products=$(./bin/dagger -m github.com/bradfordwagner/dagger-modules/container_mirror@feature/init call product --src=.) >> $GITHUB_OUTPUT
  tags:
    runs-on: arm64
    permissions: write-all
    needs: config-yaml
    name: ${{ matrix.product.repo }}-${{ matrix.product.tag }} (${{ matrix.product.arch }})
    strategy:
      fail-fast: false
      matrix:
        build: ${{ fromJSON(needs.config-yaml.outputs.products) }}
    steps:
      - name: task=tags
        run: |
          echo ${{ matrix.product }}
