name: docker-mirror-tags
on:
  push:
    tags:
      - '*'
jobs:
  config-yaml:
    name: config.yaml
    runs-on: arm64
    outputs:
      product: ${{ steps.config.outputs.product }}
    steps:
      - uses: actions/checkout@v4
      # - name: export=config
      #   id: config
      #   run: echo "config=$(yq -oj '.' config.yaml | jq -cr)" >> $GITHUB_OUTPUT
      - name: dagger=install
        run: |
          curl -L https://dl.dagger.io/dagger/install.sh | DAGGER_VERSION=0.11.8 sh
      - name: dagger=product
        id: product
        run: ./bin/dagger -m github.com/bradfordwagner/dagger-modules/container_mirror@feature/init call product --src=. >> $GITHUB_OUTPUT
